const mongoose = require("mongoose");

const journalEntrySchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Student's journal text
    text: {
      type: String,
      required: true,
      trim: true,
    },

    // AI detected emotion
    emotion: {
      type: String,
      default: "",
    },

    // Stress level (1-10)
    stressLevel: {
      type: Number,
      min: 1,
      max: 10,
      default: 1,
    },

    // Journal category
    category: {
      type: String,
      default: "",
    },

    // AI summary of the journal
    summary: {
      type: String,
      default: "",
    },

    // Personalized AI suggestions
    aiSuggestion: {
      type: String,
      default: "",
    },

    // Study advice generated by AI
    studyPlan: {
      type: String,
      default: "",
    },

    // Wellness tip
    wellnessTip: {
      type: String,
      default: "",
    },

    // Daily motivation
    motivation: {
      type: String,
      default: "",
    },

    // Optional tags
    tags: [
      {
        type: String,
      },
    ],

    // Date of journal entry
    date: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("JournalEntry", journalEntrySchema);